### ISSUE TITLE
Investigate processing of BN credentials

### ISSUE THREAD

**Issue by swcurran** [bcgov/von-bc-registries-agent#290]
We had an issue with [this](https://orgbook.gov.bc.ca/en/organization/registration.registries.ca/FM0770428) entity's BN. It might be related to the timestamp issue we are having, but there are some oddities.

Sequence of events:

- Business owner reported the issue at about 4PM on Aug. 17 that BN was old 7xxx number and should be 8xxx number.  Owner stated CRA and BC Registry had the change, OrgBook did not. Confirmed this.
- As of 9AM Aug. 18, no change.
- Audit was run at 9:30 -- update was clean.
- As of 10AM, the change was made.
   - Oddly, the old 7xxx record was gone
   - The new 8xxx record showed it was effective March 2019 -- coincident with the registration of the company.  Is that expected behavior?

Please look into this company and see if anything other than the timestamp issue (or any issue) was at play.  Perhaps BC Reg only does BN updates at 9:30 the next morning?

If all is well, please provide a brief overview of the BN handling logic -- notably the effective date of the credential.

Thanks!

**Comment by WadeBarnes** [comment]
Looking into the BC Registries data a bit, we found there was only a single filing event for that company dated `2019-03-08 16:26:36`.  That record was processed by the BC Registries Agent and the OrgBook `2019-12-18` with the original `7xxx` BN.  When the company was reprocessed on `2021-08-18` it was processed with the new `8xxx` BN.  This indicates the BN was changed some time between `2019-12-18` and `2021-08-18` and no corresponding event was generated for the change on the BC Registries side.  Without the event the BC Registries Agent does not know there has been a change to a company's records and will therefore not process the change.  @ianco to confirm if this was a manual data fix, and if there are any other types of changes that don't generate events.

**Comment by ianco** [comment]
There are two potential issues with how we process BC Registries data.  The first is as @WadeBarnes mentions above - if there is no event generated, then we will not detect the change and the update will not get posted to OrgBook.

The other issue is with any data that is in the corporation table in the source database.  Most data (such as company name, status, etc) is time sequenced - if the data changes, the record is "expired" and a new record is created - we can go back in history and see the changes in the company data over time.  However with the corporation table there is only one record, so if the BN or Company Type (for example) changes, we don't have the "old" data.  If we reprocess this company, then we generate credentials as if the corporation data (BN, company type, etc) was the same since the company was created.

**Comment by swcurran** [comment]
Do you need a contact at BC Reg to find out the behaviour?  We can get Dwayne working on that.

**Comment by ianco** [comment]
Sure would be good to get Dwayne to follow up.  He can ping me if he has any questions or needs to pull me into a call.

**Comment by swcurran** [comment]
@ianco -- is this issue now resolved such that we can close it?

**Comment by ianco** [comment]
We are waiting for a fix from registries.  We have a work-around (our nightly audit detects B mis-matches and forces updates to these companies) but would be preferable if we could get events for BN changes.
